using TylinkInspection.Core.Contracts;
using TylinkInspection.Core.Models;

namespace TylinkInspection.Services;

public sealed class RecheckSchedulerService : IRecheckSchedulerService
{
    private static readonly StringComparer TextComparer = StringComparer.OrdinalIgnoreCase;

    private readonly IRecheckTaskStore _store;
    private readonly IFaultClosureService _faultClosureService;
    private readonly IDeviceInspectionService _deviceInspectionService;
    private readonly IPlaybackReviewService _playbackReviewService;
    private readonly object _syncRoot = new();

    private readonly Dictionary<string, RecheckTaskLatestResult> _latestResults = new(StringComparer.OrdinalIgnoreCase);
    private List<RecheckTaskRecord> _tasks = [];
    private List<RecheckExecutionRecord> _executions = [];
    private RecheckRuleCatalog _ruleCatalog = RecheckRuleCatalog.CreateDefault();
    private CancellationTokenSource? _loopCts;
    private Task? _loopTask;
    private bool _started;

    private RecheckScheduleRule _activeRule => _ruleCatalog.GlobalDefaultRule;

    public RecheckSchedulerService(
        IRecheckTaskStore store,
        IFaultClosureService faultClosureService,
        IDeviceInspectionService deviceInspectionService,
        IPlaybackReviewService playbackReviewService)
    {
        _store = store;
        _faultClosureService = faultClosureService;
        _deviceInspectionService = deviceInspectionService;
        _playbackReviewService = playbackReviewService;
        _faultClosureService.OverviewChanged += OnFaultClosureOverviewChanged;
    }

    public event EventHandler? OverviewChanged;

    public void Start()
    {
        bool shouldNotify;

        lock (_syncRoot)
        {
            if (_started)
            {
                return;
            }

            _started = true;
            LoadStateNoLock();
            shouldNotify = RecoverTasksNoLock(DateTimeOffset.Now);
            PersistStateNoLock();
            _loopCts = new CancellationTokenSource();
            _loopTask = Task.Run(() => RunLoopAsync(_loopCts.Token));
        }

        Synchronize();
        if (shouldNotify)
        {
            NotifyOverviewChanged();
        }
    }

    public void Stop()
    {
        CancellationTokenSource? cts;
        Task? loopTask;

        lock (_syncRoot)
        {
            if (!_started)
            {
                return;
            }

            _started = false;
            cts = _loopCts;
            loopTask = _loopTask;
            _loopCts = null;
            _loopTask = null;
        }

        try
        {
            cts?.Cancel();
            loopTask?.Wait(TimeSpan.FromSeconds(2));
        }
        catch
        {
        }
        finally
        {
            cts?.Dispose();
        }
    }

    public void Synchronize()
    {
        EnsureStarted();

        var overview = _faultClosureService.GetOverview(new FaultClosureQuery());
        var closureLookup = overview.Records
            .Where(item => !string.IsNullOrWhiteSpace(item.RecordId))
            .ToDictionary(item => item.RecordId, StringComparer.OrdinalIgnoreCase);

        var changed = false;
        var now = DateTimeOffset.Now;

        lock (_syncRoot)
        {
            foreach (var record in overview.Records.Where(IsAutoGeneratedTaskCandidate))
            {
                var before = _tasks.FirstOrDefault(item => TextComparer.Equals(item.SourceFaultClosureId, record.RecordId));
                var ensured = EnsureTaskInternal(record, "system-sync", null, now, true);
                changed |= before is null || (ensured is not null && !TaskEquals(before, ensured));
            }

            var updatedTasks = new List<RecheckTaskRecord>(_tasks.Count);
            foreach (var task in _tasks)
            {
                if (!closureLookup.TryGetValue(task.SourceFaultClosureId, out var record))
                {
                    var canceled = FinalizeTask(
                        task,
                        RecheckTaskStatuses.Canceled,
                        false,
                        null,
                        now,
                        "源闭环记录已不存在，任务已取消。");
                    updatedTasks.Add(canceled);
                    changed |= !TaskEquals(task, canceled);
                    continue;
                }

                var reconciled = ReconcileTaskWithClosure(task, record, now);
                updatedTasks.Add(reconciled);
                changed |= !TaskEquals(task, reconciled);
            }

            if (changed)
            {
                _tasks = updatedTasks;
                PersistStateNoLock();
            }
        }

        if (changed)
        {
            NotifyOverviewChanged();
        }
    }

    public RecheckQueueOverview GetOverview()
    {
        EnsureStarted();

        lock (_syncRoot)
        {
            var now = DateTimeOffset.Now;
            var orderedTasks = _tasks
                .Select(CreateDisplayTaskSnapshotNoLock)
                .OrderBy(task => task.IsRunning ? 0 : 1)
                .ThenBy(task => task.IsEnabled && task.NextRunAt.HasValue && task.NextRunAt.Value <= now ? 0 : 1)
                .ThenBy(task => task.IsEnabled ? 0 : 1)
                .ThenBy(task => task.NextRunAt ?? DateTimeOffset.MaxValue)
                .ThenByDescending(task => task.UpdatedAt)
                .ThenBy(task => task.DeviceName, StringComparer.OrdinalIgnoreCase)
                .ToList();

            return new RecheckQueueOverview
            {
                RuleCatalog = _ruleCatalog,
                Tasks = orderedTasks,
                RecentExecutions = _executions
                    .OrderByDescending(item => item.CompletedAt)
                    .Take(60)
                    .ToList(),
                TotalCount = _tasks.Count,
                EnabledCount = _tasks.Count(item => item.IsEnabled),
                DisabledCount = _tasks.Count(item => !item.IsEnabled),
                DueCount = _tasks.Count(item => CanAutoExecute(item, now)),
                RunningCount = _tasks.Count(item => item.IsRunning),
                FailedCount = _tasks.Count(item => TextComparer.Equals(item.CurrentStatus, RecheckTaskStatuses.Failed)),
                CompletedCount = _tasks.Count(item => item.IsTerminalTask),
                GeneratedAt = now,
                StatusMessage = $"当前已纳管 {_tasks.Count} 条本地复检任务，到期任务会在客户端内自动扫描执行。"
            };
        }
    }

    public RecheckRuleCatalog GetRuleCatalog()
    {
        EnsureStarted();

        lock (_syncRoot)
        {
            return _ruleCatalog;
        }
    }

    public RecheckScheduleRule GetScheduleRule()
    {
        EnsureStarted();

        lock (_syncRoot)
        {
            return _ruleCatalog.GlobalDefaultRule;
        }
    }

    public RecheckScheduleRule SaveScheduleRule(RecheckScheduleRule rule, string operatorName)
    {
        ArgumentNullException.ThrowIfNull(rule);
        EnsureStarted();

        lock (_syncRoot)
        {
            _ruleCatalog = _ruleCatalog with
            {
                GlobalDefaultRule = NormalizeRule(rule) with
                {
                    ScopeType = RecheckRuleScopeTypes.GlobalDefault,
                    ScopeKey = string.Empty
                }
            };
            _ruleCatalog = _ruleCatalog.Normalize();
            ApplyActiveRuleToTasksNoLock(DateTimeOffset.Now);
            PersistStateNoLock();
        }

        NotifyOverviewChanged();
        return GetScheduleRule();
    }

    public RecheckScheduleRule RestoreDefaultScheduleRule(string operatorName)
    {
        EnsureStarted();
        return SaveScheduleRule(RecheckScheduleRule.CreateDefault(), operatorName);
    }

    public RecheckScheduleRule SaveFaultTypeRule(string faultType, RecheckScheduleRule rule, string operatorName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(faultType);
        ArgumentNullException.ThrowIfNull(rule);
        EnsureStarted();

        lock (_syncRoot)
        {
            var normalizedRule = NormalizeRule(rule) with
            {
                ScopeType = RecheckRuleScopeTypes.FaultType,
                ScopeKey = faultType.Trim()
            };

            _ruleCatalog = _ruleCatalog with
            {
                FaultTypeRules = _ruleCatalog.FaultTypeRules
                    .Where(item => !TextComparer.Equals(item.ScopeKey, faultType))
                    .Append(normalizedRule)
                    .ToList()
            };
            _ruleCatalog = _ruleCatalog.Normalize();
            ApplyActiveRuleToTasksNoLock(DateTimeOffset.Now);
            PersistStateNoLock();
        }

        NotifyOverviewChanged();
        return GetRuleCatalog().FaultTypeRules.First(item => TextComparer.Equals(item.ScopeKey, faultType));
    }

    public void RemoveFaultTypeRule(string faultType, string operatorName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(faultType);
        EnsureStarted();

        lock (_syncRoot)
        {
            _ruleCatalog = _ruleCatalog with
            {
                FaultTypeRules = _ruleCatalog.FaultTypeRules
                    .Where(item => !TextComparer.Equals(item.ScopeKey, faultType))
                    .ToList()
            };
            _ruleCatalog = _ruleCatalog.Normalize();
            ApplyActiveRuleToTasksNoLock(DateTimeOffset.Now);
            PersistStateNoLock();
        }

        NotifyOverviewChanged();
    }

    public RecheckTaskRecord EnsureTask(
        FaultClosureRecord sourceRecord,
        string operatorName,
        RecheckScheduleRule? scheduleRule = null)
    {
        ArgumentNullException.ThrowIfNull(sourceRecord);
        EnsureStarted();

        if (!CanManageAsTask(sourceRecord))
        {
            throw new InvalidOperationException("当前闭环记录不属于待复检队列，无法加入定时复检任务。");
        }

        RecheckTaskRecord task;
        var now = DateTimeOffset.Now;
        lock (_syncRoot)
        {
            task = EnsureTaskInternal(sourceRecord, operatorName, scheduleRule, now, true)
                ?? throw new InvalidOperationException("复检任务创建失败。");
            PersistStateNoLock();
        }

        NotifyOverviewChanged();
        return CreateDisplayTaskSnapshot(task);
    }

    public RecheckTaskRecord TriggerTaskNow(string taskId, string operatorName)
    {
        EnsureStarted();

        var prepared = PrepareTaskForExecution(taskId, operatorName, true, RecheckExecutionTriggerTypes.Manual);
        if (prepared is null)
        {
            throw new InvalidOperationException("当前任务不存在或已终态，无法手动执行。");
        }

        NotifyOverviewChanged();
        ExecutePreparedTask(prepared.Value);

        lock (_syncRoot)
        {
            return CreateDisplayTaskSnapshot(FindTaskById(taskId));
        }
    }

    public RecheckTaskRecord SetTaskEnabled(string taskId, bool isEnabled, string operatorName)
    {
        EnsureStarted();

        RecheckTaskRecord updated;
        var now = DateTimeOffset.Now;
        lock (_syncRoot)
        {
            var current = FindTaskById(taskId);
            if (current.IsTerminalTask)
            {
                throw new InvalidOperationException("终态任务不支持再次启用或停用。");
            }

            var effectiveRule = GetEffectiveRuleNoLock(current);
            updated = current with
            {
                IsEnabled = isEnabled,
                CurrentStatus = isEnabled ? ResolveEnabledStatus(effectiveRule) : current.CurrentStatus,
                NextRunAt = isEnabled ? ResolveInitialNextRunAt(effectiveRule, now, true) : null,
                MaxRetryCount = effectiveRule.MaxRetryCount,
                UpdatedAt = now,
                LastExecutionSummary = isEnabled
                    ? $"任务已由 {NormalizeOperator(operatorName)} 启用，等待下次调度。"
                    : $"任务已由 {NormalizeOperator(operatorName)} 停用。"
            };

            ReplaceTaskNoLock(updated);
            PersistStateNoLock();
        }

        NotifyOverviewChanged();
        return CreateDisplayTaskSnapshot(updated);
    }

    public RecheckTaskRecord SaveTaskRuleOverride(string taskId, RecheckScheduleRule rule, string operatorName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(taskId);
        ArgumentNullException.ThrowIfNull(rule);
        EnsureStarted();

        RecheckTaskRecord updated;
        var now = DateTimeOffset.Now;
        lock (_syncRoot)
        {
            if (!_ruleCatalog.GlobalDefaultRule.AllowManualOverride)
            {
                throw new InvalidOperationException("当前默认规则未开启手动覆盖。");
            }

            var current = FindTaskById(taskId);
            if (current.IsTerminalTask)
            {
                throw new InvalidOperationException("终态任务不支持再设置单任务规则覆盖。");
            }

            var overrideRule = NormalizeRule(rule) with
            {
                ScopeType = RecheckRuleScopeTypes.ManualOverride,
                ScopeKey = current.TaskId
            };

            updated = current with
            {
                HasManualRuleOverride = true,
                ScheduleType = overrideRule.ScheduleType,
                ScheduleRule = overrideRule,
                MaxRetryCount = overrideRule.MaxRetryCount,
                UpdatedAt = now,
                CurrentStatus = current.IsRunning ? current.CurrentStatus : ResolveEnabledStatus(overrideRule),
                NextRunAt = current.IsRunning
                    ? current.NextRunAt
                    : current.NextRunAt ?? ResolveInitialNextRunAt(overrideRule, now, current.IsEnabled),
                LastExecutionSummary = $"任务规则已由 {NormalizeOperator(operatorName)} 更新为单任务覆盖。"
            };

            ReplaceTaskNoLock(updated);
            PersistStateNoLock();
        }

        NotifyOverviewChanged();
        return CreateDisplayTaskSnapshot(updated);
    }

    public RecheckTaskRecord ClearTaskRuleOverride(string taskId, string operatorName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(taskId);
        EnsureStarted();

        RecheckTaskRecord updated;
        var now = DateTimeOffset.Now;
        lock (_syncRoot)
        {
            var current = FindTaskById(taskId);
            if (current.IsTerminalTask)
            {
                throw new InvalidOperationException("终态任务不支持再清除单任务规则覆盖。");
            }

            var resolvedRule = ResolveInheritedRuleNoLock(current);
            updated = current with
            {
                HasManualRuleOverride = false,
                ScheduleType = resolvedRule.Rule.ScheduleType,
                ScheduleRule = _ruleCatalog.GlobalDefaultRule,
                EffectiveRuleSource = resolvedRule.RuleSource,
                EffectiveRuleScopeType = resolvedRule.Rule.ScopeType,
                EffectiveRuleScopeKey = resolvedRule.ScopeKey,
                MaxRetryCount = resolvedRule.Rule.MaxRetryCount,
                UpdatedAt = now,
                CurrentStatus = current.IsRunning ? current.CurrentStatus : ResolveEnabledStatus(resolvedRule.Rule),
                NextRunAt = current.IsRunning
                    ? current.NextRunAt
                    : current.NextRunAt ?? ResolveInitialNextRunAt(resolvedRule.Rule, now, current.IsEnabled),
                LastExecutionSummary = $"任务规则已由 {NormalizeOperator(operatorName)} 恢复为继承规则。"
            };

            ReplaceTaskNoLock(updated);
            PersistStateNoLock();
        }

        NotifyOverviewChanged();
        return CreateDisplayTaskSnapshot(updated);
    }

    private async Task RunLoopAsync(CancellationToken cancellationToken)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            try
            {
                await Task.Delay(GetScanInterval(), cancellationToken);
            }
            catch (OperationCanceledException)
            {
                break;
            }

            while (true)
            {
                var prepared = PrepareNextDueTaskForExecution();
                if (prepared is null)
                {
                    break;
                }

                NotifyOverviewChanged();
                ExecutePreparedTask(prepared.Value);
            }
        }
    }

    private void OnFaultClosureOverviewChanged(object? sender, EventArgs e)
    {
        if (!_started)
        {
            return;
        }

        try
        {
            Synchronize();
        }
        catch
        {
        }
    }

    private PreparedTaskExecution? PrepareNextDueTaskForExecution()
    {
        EnsureStarted();

        lock (_syncRoot)
        {
            var now = DateTimeOffset.Now;
            var task = _tasks
                .Where(item => CanAutoExecute(item, now))
                .OrderBy(item => item.NextRunAt)
                .ThenBy(item => item.UpdatedAt)
                .FirstOrDefault();

            if (task is null)
            {
                return null;
            }

            var triggerType = task.RetryCount > 0 || TextComparer.Equals(task.CurrentStatus, RecheckTaskStatuses.Failed)
                ? RecheckExecutionTriggerTypes.Retry
                : RecheckExecutionTriggerTypes.Scheduled;

            return PrepareTaskForExecutionNoLock(task, "system-scheduler", triggerType, now);
        }
    }

    private PreparedTaskExecution? PrepareTaskForExecution(
        string taskId,
        string operatorName,
        bool allowDisabledTask,
        string triggerType)
    {
        lock (_syncRoot)
        {
            var task = _tasks.FirstOrDefault(item => TextComparer.Equals(item.TaskId, taskId));
            if (task is null || task.IsTerminalTask || task.IsRunning)
            {
                return null;
            }

            if (!allowDisabledTask && !task.IsEnabled)
            {
                return null;
            }

            return PrepareTaskForExecutionNoLock(task, operatorName, triggerType, DateTimeOffset.Now);
        }
    }

    private PreparedTaskExecution PrepareTaskForExecutionNoLock(
        RecheckTaskRecord task,
        string operatorName,
        string triggerType,
        DateTimeOffset startedAt)
    {
        var resolvedRule = ResolveRuleSelectionNoLock(task);
        var effectiveRule = resolvedRule.Rule;
        var running = task with
        {
            CurrentStatus = RecheckTaskStatuses.Running,
            ScheduleType = effectiveRule.ScheduleType,
            ScheduleRule = task.HasManualRuleOverride ? task.ScheduleRule.Normalize() : effectiveRule,
            EffectiveRuleSource = resolvedRule.RuleSource,
            EffectiveRuleScopeType = effectiveRule.ScopeType,
            EffectiveRuleScopeKey = resolvedRule.ScopeKey,
            MaxRetryCount = effectiveRule.MaxRetryCount,
            UpdatedAt = startedAt,
            LastExecutionSummary = $"{RecheckTextMapper.ToTriggerTypeText(triggerType)}已开始执行。"
        };

        ReplaceTaskNoLock(running);
        PersistStateNoLock();

        return new PreparedTaskExecution(running, NormalizeOperator(operatorName), triggerType, startedAt, resolvedRule);
    }

    private void ExecutePreparedTask(PreparedTaskExecution prepared)
    {
        var executionResult = ExecuteCore(prepared.Task, prepared.OperatorName, prepared.TriggerType, prepared.StartedAt);

        lock (_syncRoot)
        {
            var current = FindTaskById(prepared.Task.TaskId);
            var updatedTask = ApplyExecutionResult(current, executionResult, prepared.StartedAt, prepared.RuleSelection);
            var executionRecord = BuildExecutionRecord(prepared.Task, executionResult, prepared.TriggerType, prepared.StartedAt, prepared.RuleSelection);

            ReplaceTaskNoLock(updatedTask);
            _executions.RemoveAll(item => TextComparer.Equals(item.ExecutionId, executionRecord.ExecutionId));
            _executions.Add(executionRecord);
            _latestResults[updatedTask.TaskId] = BuildLatestResult(updatedTask, executionRecord);

            PersistStateNoLock();
        }

        NotifyOverviewChanged();
    }

    private TaskExecutionResult ExecuteCore(
        RecheckTaskRecord task,
        string operatorName,
        string triggerType,
        DateTimeOffset startedAt)
    {
        FaultClosureRecord? closureRecord;
        try
        {
            closureRecord = _faultClosureService.GetOverview(new FaultClosureQuery())
                .Records
                .FirstOrDefault(item => TextComparer.Equals(item.RecordId, task.SourceFaultClosureId));
        }
        catch (Exception ex)
        {
            return TaskExecutionResult.Error(
                "闭环中心读取失败，复检任务将在下个周期重试。",
                ex.Message);
        }

        if (closureRecord is null)
        {
            return TaskExecutionResult.Canceled("源闭环记录不存在，任务已取消。");
        }

        if (string.Equals(closureRecord.CurrentStatus, FaultClosureStatuses.RecheckPassedPendingClear, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(closureRecord.CurrentStatus, FaultClosureStatuses.Cleared, StringComparison.OrdinalIgnoreCase))
        {
            return TaskExecutionResult.Completed(
                closureRecord.CurrentStatus,
                "闭环记录已进入待销警/已销警状态，任务已完成。");
        }

        if (closureRecord.IsTerminal)
        {
            return TaskExecutionResult.Canceled(
                $"闭环记录已进入终态 {closureRecord.StatusText}，任务已取消。",
                closureRecord.CurrentStatus);
        }

        try
        {
            var updatedClosure = _faultClosureService.RunRecheck(task.SourceFaultClosureId, operatorName);
            var inspectionResult = _deviceInspectionService.GetLatestResult(task.DeviceCode);
            var lightweightReview = TryPrepareLightPlaybackReview(task, inspectionResult);
            var summary = BuildExecutionSummary(updatedClosure, inspectionResult, lightweightReview, triggerType, startedAt);

            if (string.Equals(updatedClosure.CurrentStatus, FaultClosureStatuses.RecheckPassedPendingClear, StringComparison.OrdinalIgnoreCase))
            {
                return TaskExecutionResult.Passed(
                    updatedClosure.CurrentStatus,
                    summary,
                    inspectionResult,
                    lightweightReview?.SessionId);
            }

            return TaskExecutionResult.Failed(
                updatedClosure.CurrentStatus,
                summary,
                inspectionResult,
                inspectionResult?.FailureReason ?? string.Empty,
                lightweightReview?.SessionId);
        }
        catch (Exception ex)
        {
            return TaskExecutionResult.Error(
                "复检执行过程中发生异常，任务已进入失败重试。",
                ex.Message);
        }
    }

    private PlaybackReviewSession? TryPrepareLightPlaybackReview(
        RecheckTaskRecord task,
        DeviceInspectionResult? inspectionResult)
    {
        var effectiveRule = GetEffectiveRule(task);
        if (!effectiveRule.UseLightPlaybackReview ||
            inspectionResult is null ||
            (!inspectionResult.IsAbnormal &&
             inspectionResult.HasPreferredUrl &&
             inspectionResult.PlaybackHealthGrade is not PlaybackHealthGrade.D and not PlaybackHealthGrade.E))
        {
            return null;
        }

        try
        {
            return _playbackReviewService.PrepareLiveReview(new PlaybackReviewPreparationRequest
            {
                DeviceCode = task.DeviceCode,
                DeviceName = task.DeviceName,
                BaseInspectionResult = inspectionResult,
                ForceRefresh = true
            });
        }
        catch
        {
            return null;
        }
    }

    private RecheckTaskRecord ApplyExecutionResult(
        RecheckTaskRecord current,
        TaskExecutionResult executionResult,
        DateTimeOffset startedAt,
        ResolvedRuleSelection ruleSelection)
    {
        var now = DateTimeOffset.Now;
        var effectiveRule = ruleSelection.Rule;
        var nextRetryCount = current.RetryCount;
        DateTimeOffset? nextRunAt = null;
        var currentStatus = executionResult.TaskStatus;
        var isEnabled = current.IsEnabled;

        switch (executionResult.ResultKind)
        {
            case ExecutionResultKind.Passed:
            case ExecutionResultKind.Completed:
            case ExecutionResultKind.Canceled:
                nextRetryCount = 0;
                nextRunAt = null;
                isEnabled = false;
                break;
            case ExecutionResultKind.Failed:
                nextRetryCount = 0;
                nextRunAt = current.IsEnabled
                    ? ResolveNextRunAt(effectiveRule, now, false)
                    : null;
                break;
            case ExecutionResultKind.Error:
                var attemptedRetryCount = current.RetryCount + 1;
                nextRetryCount = Math.Min(effectiveRule.MaxRetryCount, attemptedRetryCount);
                nextRunAt = current.IsEnabled
                    ? ResolveNextRunAt(effectiveRule, now, attemptedRetryCount <= effectiveRule.MaxRetryCount)
                    : null;
                break;
        }

        return current with
        {
            CurrentStatus = currentStatus,
            IsEnabled = isEnabled,
            ScheduleType = effectiveRule.ScheduleType,
            ScheduleRule = current.HasManualRuleOverride ? current.ScheduleRule.Normalize() : effectiveRule,
            EffectiveRuleSource = ruleSelection.RuleSource,
            EffectiveRuleScopeType = effectiveRule.ScopeType,
            EffectiveRuleScopeKey = ruleSelection.ScopeKey,
            NextRunAt = nextRunAt,
            LastRunAt = startedAt,
            RetryCount = nextRetryCount,
            MaxRetryCount = effectiveRule.MaxRetryCount,
            UpdatedAt = now,
            LastExecutionId = executionResult.ExecutionId,
            LastExecutionSummary = executionResult.Summary,
            LastExecutionOutcome = executionResult.Outcome,
            LastFaultClosureStatus = executionResult.FaultClosureStatus,
            LastResultAt = now,
            LastFailureReason = executionResult.FailureReason,
            LastPlaybackReviewSessionId = executionResult.PlaybackReviewSessionId
        };
    }

    private RecheckExecutionRecord BuildExecutionRecord(
        RecheckTaskRecord task,
        TaskExecutionResult executionResult,
        string triggerType,
        DateTimeOffset startedAt,
        ResolvedRuleSelection ruleSelection)
    {
        return new RecheckExecutionRecord
        {
            ExecutionId = executionResult.ExecutionId,
            TaskId = task.TaskId,
            SourceFaultClosureId = task.SourceFaultClosureId,
            DeviceCode = task.DeviceCode,
            DeviceName = task.DeviceName,
            FaultType = task.FaultType,
            TriggerType = triggerType,
            StartedAt = startedAt,
            CompletedAt = DateTimeOffset.Now,
            Outcome = executionResult.Outcome,
            TaskStatusAfter = executionResult.TaskStatus,
            FaultClosureStatusAfter = executionResult.FaultClosureStatus,
            AppliedRuleSource = ruleSelection.RuleSource,
            AppliedRuleScopeType = ruleSelection.Rule.ScopeType,
            AppliedRuleScopeKey = ruleSelection.ScopeKey,
            AppliedRuleSummary = ruleSelection.Rule.RuleSummaryText,
            OnlineStatus = executionResult.InspectionResult?.OnlineStatus,
            PlaybackHealthGrade = executionResult.InspectionResult?.PlaybackHealthGrade ?? PlaybackHealthGrade.E,
            PreferredProtocol = executionResult.InspectionResult?.PreferredProtocol ?? string.Empty,
            Summary = executionResult.Summary,
            FailureReason = executionResult.FailureReason,
            RelatedPlaybackReviewSessionId = executionResult.PlaybackReviewSessionId
        };
    }

    private static RecheckTaskLatestResult BuildLatestResult(
        RecheckTaskRecord task,
        RecheckExecutionRecord executionRecord)
    {
        return new RecheckTaskLatestResult
        {
            TaskId = task.TaskId,
            ExecutionId = executionRecord.ExecutionId,
            DeviceCode = task.DeviceCode,
            DeviceName = task.DeviceName,
            Outcome = executionRecord.Outcome,
            TaskStatus = executionRecord.TaskStatusAfter,
            FaultClosureStatus = executionRecord.FaultClosureStatusAfter,
            ResultAt = executionRecord.CompletedAt,
            Summary = executionRecord.Summary,
            FailureReason = executionRecord.FailureReason,
            PreferredProtocol = executionRecord.PreferredProtocol,
            OnlineStatus = executionRecord.OnlineStatus,
            PlaybackHealthGrade = executionRecord.PlaybackHealthGrade,
            RelatedPlaybackReviewSessionId = executionRecord.RelatedPlaybackReviewSessionId
        };
    }

    private RecheckTaskRecord? EnsureTaskInternal(
        FaultClosureRecord sourceRecord,
        string operatorName,
        RecheckScheduleRule? scheduleRule,
        DateTimeOffset now,
        bool activateExistingTerminalTask)
    {
        var current = _tasks.FirstOrDefault(item => TextComparer.Equals(item.SourceFaultClosureId, sourceRecord.RecordId));
        var hasManualOverride = scheduleRule is not null && _ruleCatalog.GlobalDefaultRule.AllowManualOverride;
        if (current is not null && current.HasManualRuleOverride && scheduleRule is null && _ruleCatalog.GlobalDefaultRule.AllowManualOverride)
        {
            hasManualOverride = true;
        }

        var resolvedRule = ResolveEffectiveRuleForEnsure(sourceRecord.FaultType, current, scheduleRule);
        var effectiveRule = resolvedRule.Rule;

        if (current is not null && current.IsTerminalTask && !activateExistingTerminalTask)
        {
            return current;
        }

        if (current is not null && !current.IsTerminalTask)
        {
            var preserved = current with
            {
                DeviceCode = sourceRecord.DeviceCode,
                DeviceName = string.IsNullOrWhiteSpace(sourceRecord.DeviceName) ? sourceRecord.DeviceCode : sourceRecord.DeviceName,
                FaultType = sourceRecord.FaultType,
                ScheduleType = effectiveRule.ScheduleType,
                ScheduleRule = hasManualOverride ? effectiveRule : _ruleCatalog.GlobalDefaultRule,
                EffectiveRuleSource = resolvedRule.RuleSource,
                EffectiveRuleScopeType = effectiveRule.ScopeType,
                EffectiveRuleScopeKey = resolvedRule.ScopeKey,
                MaxRetryCount = effectiveRule.MaxRetryCount,
                HasManualRuleOverride = hasManualOverride,
                UpdatedAt = current.UpdatedAt,
                LastFaultClosureStatus = sourceRecord.CurrentStatus
            };

            if (preserved.IsEnabled && !preserved.NextRunAt.HasValue)
            {
                preserved = preserved with
                {
                    NextRunAt = ResolveInitialNextRunAt(effectiveRule, now, true),
                    CurrentStatus = ResolveEnabledStatus(effectiveRule),
                    UpdatedAt = now
                };
            }

            ReplaceTaskNoLock(preserved);
            return preserved;
        }

        var isEnabled = current is not null && !current.IsTerminalTask ? current.IsEnabled : true;
        var updated = new RecheckTaskRecord
        {
            TaskId = current?.TaskId ?? Guid.NewGuid().ToString("N"),
            DeviceCode = sourceRecord.DeviceCode,
            DeviceName = string.IsNullOrWhiteSpace(sourceRecord.DeviceName) ? sourceRecord.DeviceCode : sourceRecord.DeviceName,
            FaultType = sourceRecord.FaultType,
            SourceFaultClosureId = sourceRecord.RecordId,
            CurrentStatus = isEnabled ? ResolveEnabledStatus(effectiveRule) : RecheckTaskStatuses.Pending,
            ScheduleType = effectiveRule.ScheduleType,
            NextRunAt = ResolveInitialNextRunAt(effectiveRule, now, isEnabled),
            LastRunAt = current?.LastRunAt,
            RetryCount = current?.RetryCount ?? 0,
            MaxRetryCount = effectiveRule.MaxRetryCount,
            IsEnabled = isEnabled,
            HasManualRuleOverride = hasManualOverride,
            EffectiveRuleSource = resolvedRule.RuleSource,
            EffectiveRuleScopeType = effectiveRule.ScopeType,
            EffectiveRuleScopeKey = resolvedRule.ScopeKey,
            CreatedAt = current?.CreatedAt ?? now,
            UpdatedAt = now,
            ScheduleRule = hasManualOverride ? effectiveRule : _ruleCatalog.GlobalDefaultRule,
            LastExecutionId = current?.LastExecutionId ?? string.Empty,
            LastExecutionSummary = current?.LastExecutionSummary ?? $"任务已加入本地复检队列，等待 {effectiveRule.ScheduleTypeText} 调度。",
            LastExecutionOutcome = current?.LastExecutionOutcome ?? string.Empty,
            LastFaultClosureStatus = current?.LastFaultClosureStatus ?? sourceRecord.CurrentStatus,
            LastResultAt = current?.LastResultAt,
            LastFailureReason = current?.LastFailureReason ?? string.Empty,
            LastPlaybackReviewSessionId = current?.LastPlaybackReviewSessionId ?? string.Empty
        };

        if (!updated.IsEnabled)
        {
            updated = updated with
            {
                NextRunAt = null,
                LastExecutionSummary = current?.LastExecutionSummary ?? $"任务已由 {NormalizeOperator(operatorName)} 创建，但当前保持停用。"
            };
        }

        ReplaceTaskNoLock(updated);
        return updated;
    }

    private RecheckTaskRecord ReconcileTaskWithClosure(
        RecheckTaskRecord task,
        FaultClosureRecord closureRecord,
        DateTimeOffset now)
    {
        if (task.IsRunning)
        {
            return task;
        }

        if (string.Equals(closureRecord.CurrentStatus, FaultClosureStatuses.RecheckPassedPendingClear, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(closureRecord.CurrentStatus, FaultClosureStatuses.Cleared, StringComparison.OrdinalIgnoreCase))
        {
            return FinalizeTask(
                task,
                RecheckTaskStatuses.Completed,
                false,
                closureRecord.CurrentStatus,
                now,
                "闭环状态已流转为待销警/已销警，复检任务已完成。");
        }

        if (closureRecord.IsTerminal)
        {
            return FinalizeTask(
                task,
                RecheckTaskStatuses.Canceled,
                false,
                closureRecord.CurrentStatus,
                now,
                $"闭环记录已进入终态 {closureRecord.StatusText}，复检任务已取消。");
        }

        var effectiveRule = GetEffectiveRuleNoLock(task);
        var resolvedRule = ResolveRuleSelectionNoLock(task);
        return task with
        {
            DeviceCode = closureRecord.DeviceCode,
            DeviceName = closureRecord.DeviceName,
            FaultType = closureRecord.FaultType,
            ScheduleType = effectiveRule.ScheduleType,
            ScheduleRule = task.HasManualRuleOverride ? task.ScheduleRule.Normalize() : effectiveRule,
            EffectiveRuleSource = resolvedRule.RuleSource,
            EffectiveRuleScopeType = effectiveRule.ScopeType,
            EffectiveRuleScopeKey = resolvedRule.ScopeKey,
            MaxRetryCount = effectiveRule.MaxRetryCount,
            LastFaultClosureStatus = closureRecord.CurrentStatus
        };
    }

    private static RecheckTaskRecord FinalizeTask(
        RecheckTaskRecord task,
        string status,
        bool isEnabled,
        string? faultClosureStatus,
        DateTimeOffset updatedAt,
        string summary)
    {
        return task with
        {
            CurrentStatus = status,
            IsEnabled = isEnabled,
            NextRunAt = null,
            UpdatedAt = updatedAt,
            LastFaultClosureStatus = faultClosureStatus ?? task.LastFaultClosureStatus,
            LastExecutionSummary = summary,
            LastExecutionOutcome = string.Equals(status, RecheckTaskStatuses.Completed, StringComparison.OrdinalIgnoreCase)
                ? RecheckExecutionOutcomes.Completed
                : RecheckExecutionOutcomes.Canceled,
            LastResultAt = updatedAt
        };
    }

    private void LoadStateNoLock()
    {
        _ruleCatalog = _store.LoadRuleCatalog().Normalize();
        _tasks = _store.LoadTasks()
            .Select(NormalizeTaskAfterLoad)
            .ToList();
        _executions = _store.LoadExecutions()
            .OrderBy(item => item.CompletedAt)
            .ToList();
        _latestResults.Clear();
        foreach (var result in _store.LoadLatestResults())
        {
            if (!string.IsNullOrWhiteSpace(result.TaskId))
            {
                _latestResults[result.TaskId] = result;
            }
        }

        ApplyActiveRuleToTasksNoLock(DateTimeOffset.Now);
    }

    private void PersistStateNoLock()
    {
        _store.SaveRuleCatalog(_ruleCatalog);
        _store.SaveTasks(_tasks
            .OrderBy(item => item.DeviceCode, StringComparer.OrdinalIgnoreCase)
            .ThenBy(item => item.CreatedAt)
            .ToList());
        _store.SaveExecutions(_executions
            .OrderByDescending(item => item.CompletedAt)
            .Take(600)
            .ToList());
        _store.SaveLatestResults(_latestResults.Values
            .OrderByDescending(item => item.ResultAt)
            .ToList());
    }

    private bool RecoverTasksNoLock(DateTimeOffset now)
    {
        var changed = false;
        var recovered = new List<RecheckTaskRecord>(_tasks.Count);

        foreach (var task in _tasks)
        {
            if (!task.IsRunning)
            {
                recovered.Add(task);
                continue;
            }

            var effectiveRule = GetEffectiveRuleNoLock(task);
            recovered.Add(task with
            {
                CurrentStatus = ResolveEnabledStatus(effectiveRule),
                NextRunAt = ResolveNextRunAt(effectiveRule, now, true),
                UpdatedAt = now,
                LastExecutionSummary = "检测到上次客户端退出时任务处于执行中，已恢复为待调度状态。"
            });
            changed = true;
        }

        if (changed)
        {
            _tasks = recovered;
        }

        return changed;
    }

    private void ReplaceTaskNoLock(RecheckTaskRecord updated)
    {
        for (var index = 0; index < _tasks.Count; index += 1)
        {
            if (!TextComparer.Equals(_tasks[index].TaskId, updated.TaskId))
            {
                continue;
            }

            _tasks[index] = updated;
            return;
        }

        _tasks.Add(updated);
    }

    private RecheckTaskRecord FindTaskById(string taskId)
    {
        var task = _tasks.FirstOrDefault(item => TextComparer.Equals(item.TaskId, taskId));
        return task ?? throw new InvalidOperationException("未找到复检任务。");
    }

    private static bool IsAutoGeneratedTaskCandidate(FaultClosureRecord record)
    {
        return record.RequiresRecheck &&
               string.Equals(record.CurrentStatus, FaultClosureStatuses.PendingRecheck, StringComparison.OrdinalIgnoreCase);
    }

    private static bool CanManageAsTask(FaultClosureRecord record)
    {
        return !record.IsTerminal &&
               record.RequiresRecheck &&
               string.Equals(record.CurrentStatus, FaultClosureStatuses.PendingRecheck, StringComparison.OrdinalIgnoreCase);
    }

    private bool CanAutoExecute(RecheckTaskRecord task, DateTimeOffset now)
    {
        var effectiveRule = GetEffectiveRuleNoLock(task);
        return effectiveRule.IsAutoRecheckEnabled &&
               task.IsEnabled &&
               !task.IsTerminalTask &&
               !task.IsRunning &&
               task.NextRunAt.HasValue &&
               task.NextRunAt.Value <= now &&
               !string.Equals(effectiveRule.ScheduleType, RecheckScheduleTypes.ManualOnly, StringComparison.OrdinalIgnoreCase);
    }

    private static DateTimeOffset? ResolveInitialNextRunAt(
        RecheckScheduleRule rule,
        DateTimeOffset now,
        bool isEnabled)
    {
        if (!isEnabled || !rule.IsAutoRecheckEnabled)
        {
            return null;
        }

        if (string.Equals(rule.ScheduleType, RecheckScheduleTypes.ManualOnly, StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        if (string.Equals(rule.ScheduleType, RecheckScheduleTypes.SpecificTime, StringComparison.OrdinalIgnoreCase))
        {
            return rule.PlannedRunAt.HasValue && rule.PlannedRunAt.Value > now
                ? rule.PlannedRunAt.Value
                : now.AddMinutes(Math.Max(0, rule.InitialDelayMinutes));
        }

        return now.AddMinutes(Math.Max(0, rule.InitialDelayMinutes));
    }

    private static DateTimeOffset? ResolveNextRunAt(
        RecheckScheduleRule rule,
        DateTimeOffset now,
        bool preferRetryWindow)
    {
        if (!rule.IsAutoRecheckEnabled ||
            string.Equals(rule.ScheduleType, RecheckScheduleTypes.ManualOnly, StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        if (string.Equals(rule.ScheduleType, RecheckScheduleTypes.SpecificTime, StringComparison.OrdinalIgnoreCase))
        {
            return rule.PlannedRunAt.HasValue && rule.PlannedRunAt.Value > now
                ? rule.PlannedRunAt.Value
                : now.AddMinutes(preferRetryWindow
                    ? Math.Max(1, rule.RetryDelayMinutes)
                    : Math.Max(1, rule.IntervalMinutes));
        }

        var delayMinutes = preferRetryWindow
            ? Math.Max(1, rule.RetryDelayMinutes)
            : Math.Max(1, rule.IntervalMinutes);

        return now.AddMinutes(delayMinutes);
    }

    private static string BuildExecutionSummary(
        FaultClosureRecord closureRecord,
        DeviceInspectionResult? inspectionResult,
        PlaybackReviewSession? lightweightReview,
        string triggerType,
        DateTimeOffset startedAt)
    {
        var segments = new List<string>
        {
            $"{RecheckTextMapper.ToTriggerTypeText(triggerType)} {startedAt:HH:mm:ss}"
        };

        if (inspectionResult is not null)
        {
            segments.Add(inspectionResult.PlaybackHealthSummary);
            if (!string.IsNullOrWhiteSpace(inspectionResult.RecheckText))
            {
                segments.Add(inspectionResult.RecheckText);
            }
        }

        if (lightweightReview is not null)
        {
            segments.Add(string.IsNullOrWhiteSpace(lightweightReview.PreferredProtocol)
                ? "已尝试轻量播放预复核"
                : $"轻量播放 {lightweightReview.PreferredProtocol}");
        }

        segments.Add(closureRecord.StatusText);
        return string.Join(" / ", segments.Where(item => !string.IsNullOrWhiteSpace(item)));
    }

    private static string BuildCreatedSummary(string operatorName, RecheckScheduleRule rule, bool isEnabled)
    {
        if (!isEnabled)
        {
            return $"任务已由 {NormalizeOperator(operatorName)} 创建，当前保持停用。";
        }

        if (!rule.IsAutoRecheckEnabled)
        {
            return "任务已加入本地复检队列，当前自动复检停用，可继续手动触发。";
        }

        return $"任务已加入本地复检队列，将按“{rule.RuleSummaryText}”调度执行。";
    }

    private static string BuildEnabledSummary(string operatorName, RecheckScheduleRule rule)
    {
        return rule.IsAutoRecheckEnabled
            ? $"任务已由 {NormalizeOperator(operatorName)} 启用，等待下一次调度。"
            : $"任务已由 {NormalizeOperator(operatorName)} 启用，但当前自动复检停用。";
    }

    private string BuildQueueStatusMessage(DateTimeOffset now)
    {
        var dueCount = _tasks.Count(item => CanAutoExecute(item, now));
        var autoText = _activeRule.IsAutoRecheckEnabled
            ? $"自动复检开启，调度扫描每 {_activeRule.ScanIntervalSeconds} 秒执行一次。"
            : "自动复检已停用，仅保留本地任务和手动触发能力。";

        return $"当前已纳管 {_tasks.Count} 条本地复检任务，待执行 {dueCount} 条。{autoText}";
    }

    private TimeSpan GetScanInterval()
    {
        lock (_syncRoot)
        {
            return TimeSpan.FromSeconds(Math.Max(5, _activeRule.ScanIntervalSeconds));
        }
    }

    private void ApplyActiveRuleToTasksNoLock(DateTimeOffset now)
    {
        var updatedTasks = new List<RecheckTaskRecord>(_tasks.Count);

        foreach (var task in _tasks)
        {
            var resolvedRule = ResolveRuleSelectionNoLock(task);
            var effectiveRule = resolvedRule.Rule;
            var updatedTask = task with
            {
                ScheduleType = effectiveRule.ScheduleType,
                ScheduleRule = task.HasManualRuleOverride ? task.ScheduleRule.Normalize() : _ruleCatalog.GlobalDefaultRule,
                EffectiveRuleSource = resolvedRule.RuleSource,
                EffectiveRuleScopeType = effectiveRule.ScopeType,
                EffectiveRuleScopeKey = resolvedRule.ScopeKey,
                MaxRetryCount = effectiveRule.MaxRetryCount
            };

            if (!updatedTask.IsRunning && updatedTask.IsEnabled && !updatedTask.NextRunAt.HasValue)
            {
                updatedTask = updatedTask with
                {
                    CurrentStatus = ResolveEnabledStatus(effectiveRule),
                    NextRunAt = ResolveInitialNextRunAt(effectiveRule, now, true)
                };
            }

            updatedTasks.Add(updatedTask);
        }

        _tasks = updatedTasks;
    }

    private RecheckTaskRecord NormalizeTaskAfterLoad(RecheckTaskRecord task)
    {
        var normalizedRule = task.ScheduleRule?.Normalize() ?? RecheckScheduleRule.CreateDefault();
        return task with
        {
            FaultType = task.FaultType?.Trim() ?? string.Empty,
            ScheduleType = string.IsNullOrWhiteSpace(task.ScheduleType) ? normalizedRule.ScheduleType : task.ScheduleType,
            ScheduleRule = normalizedRule,
            MaxRetryCount = task.MaxRetryCount > 0 ? task.MaxRetryCount : normalizedRule.MaxRetryCount,
            EffectiveRuleSource = string.IsNullOrWhiteSpace(task.EffectiveRuleSource) ? RecheckRuleHitSources.GlobalDefault : task.EffectiveRuleSource,
            EffectiveRuleScopeType = string.IsNullOrWhiteSpace(task.EffectiveRuleScopeType) ? RecheckRuleScopeTypes.GlobalDefault : task.EffectiveRuleScopeType,
            EffectiveRuleScopeKey = task.EffectiveRuleScopeKey?.Trim() ?? string.Empty
        };
    }

    private RecheckTaskRecord CreateDisplayTaskSnapshot(RecheckTaskRecord task)
    {
        lock (_syncRoot)
        {
            return CreateDisplayTaskSnapshotNoLock(task);
        }
    }

    private RecheckTaskRecord CreateDisplayTaskSnapshotNoLock(RecheckTaskRecord task)
    {
        var resolvedRule = ResolveRuleSelectionNoLock(task);
        var effectiveRule = resolvedRule.Rule;
        return task with
        {
            ScheduleType = effectiveRule.ScheduleType,
            ScheduleRule = effectiveRule,
            EffectiveRuleSource = resolvedRule.RuleSource,
            EffectiveRuleScopeType = effectiveRule.ScopeType,
            EffectiveRuleScopeKey = resolvedRule.ScopeKey,
            MaxRetryCount = effectiveRule.MaxRetryCount
        };
    }

    private ResolvedRuleSelection ResolveEffectiveRuleForEnsure(
        string faultType,
        RecheckTaskRecord? current,
        RecheckScheduleRule? requestedRule)
    {
        if (requestedRule is not null && _ruleCatalog.GlobalDefaultRule.AllowManualOverride)
        {
            var overrideRule = NormalizeRule(requestedRule) with
            {
                ScopeType = RecheckRuleScopeTypes.ManualOverride,
                ScopeKey = current?.TaskId ?? string.Empty
            };
            return new ResolvedRuleSelection(overrideRule, RecheckRuleHitSources.ManualOverride, current?.TaskId ?? string.Empty);
        }

        if (current is not null && current.HasManualRuleOverride && _ruleCatalog.GlobalDefaultRule.AllowManualOverride)
        {
            return new ResolvedRuleSelection(
                NormalizeRule(current.ScheduleRule) with
                {
                    ScopeType = RecheckRuleScopeTypes.ManualOverride,
                    ScopeKey = current.TaskId
                },
                RecheckRuleHitSources.ManualOverride,
                current.TaskId);
        }

        return ResolveInheritedRuleNoLock(faultType);
    }

    private RecheckScheduleRule GetEffectiveRule(RecheckTaskRecord task)
    {
        lock (_syncRoot)
        {
            return GetEffectiveRuleNoLock(task);
        }
    }

    private RecheckScheduleRule GetEffectiveRuleNoLock(RecheckTaskRecord task)
    {
        return ResolveRuleSelectionNoLock(task).Rule;
    }

    private ResolvedRuleSelection ResolveRuleSelectionNoLock(RecheckTaskRecord task)
    {
        if (task.HasManualRuleOverride && _ruleCatalog.GlobalDefaultRule.AllowManualOverride)
        {
            return new ResolvedRuleSelection(
                NormalizeRule(task.ScheduleRule) with
                {
                    ScopeType = RecheckRuleScopeTypes.ManualOverride,
                    ScopeKey = task.TaskId
                },
                RecheckRuleHitSources.ManualOverride,
                task.TaskId);
        }

        return ResolveInheritedRuleNoLock(task);
    }

    private ResolvedRuleSelection ResolveInheritedRuleNoLock(RecheckTaskRecord task)
    {
        return ResolveInheritedRuleNoLock(task.FaultType);
    }

    private ResolvedRuleSelection ResolveInheritedRuleNoLock(string? faultType)
    {
        if (!string.IsNullOrWhiteSpace(faultType))
        {
            var faultTypeRule = _ruleCatalog.FaultTypeRules.FirstOrDefault(item =>
                TextComparer.Equals(item.ScopeKey, faultType));
            if (faultTypeRule is not null)
            {
                var normalizedFaultTypeRule = NormalizeRule(faultTypeRule) with
                {
                    ScopeType = RecheckRuleScopeTypes.FaultType,
                    ScopeKey = faultType.Trim()
                };
                return new ResolvedRuleSelection(
                    normalizedFaultTypeRule,
                    RecheckRuleHitSources.FaultTypeRule,
                    faultType.Trim());
            }
        }

        return new ResolvedRuleSelection(
            _ruleCatalog.GlobalDefaultRule,
            RecheckRuleHitSources.GlobalDefault,
            string.Empty);
    }

    private static string ResolveEnabledStatus(RecheckScheduleRule rule)
    {
        return rule.IsAutoRecheckEnabled &&
               !string.Equals(rule.ScheduleType, RecheckScheduleTypes.ManualOnly, StringComparison.OrdinalIgnoreCase)
            ? RecheckTaskStatuses.Scheduled
            : RecheckTaskStatuses.Pending;
    }

    private void EnsureStarted()
    {
        if (!_started)
        {
            Start();
        }
    }

    private void NotifyOverviewChanged()
    {
        OverviewChanged?.Invoke(this, EventArgs.Empty);
    }

    private static RecheckScheduleRule NormalizeRule(RecheckScheduleRule rule)
    {
        var normalized = rule.Normalize();
        return string.IsNullOrWhiteSpace(normalized.RuleId)
            ? normalized with { RuleId = Guid.NewGuid().ToString("N") }
            : normalized;
    }

    private static string NormalizeOperator(string? operatorName)
    {
        if (!string.IsNullOrWhiteSpace(operatorName))
        {
            return operatorName.Trim();
        }

        return string.IsNullOrWhiteSpace(Environment.UserName)
            ? "current-operator"
            : Environment.UserName.Trim();
    }

    private static bool TaskEquals(RecheckTaskRecord left, RecheckTaskRecord right)
    {
        return left.TaskId == right.TaskId &&
               left.CurrentStatus == right.CurrentStatus &&
               left.ScheduleType == right.ScheduleType &&
               left.NextRunAt == right.NextRunAt &&
               left.LastRunAt == right.LastRunAt &&
               left.RetryCount == right.RetryCount &&
               left.MaxRetryCount == right.MaxRetryCount &&
               left.IsEnabled == right.IsEnabled &&
               left.HasManualRuleOverride == right.HasManualRuleOverride &&
               left.FaultType == right.FaultType &&
               left.EffectiveRuleSource == right.EffectiveRuleSource &&
               left.EffectiveRuleScopeType == right.EffectiveRuleScopeType &&
               left.EffectiveRuleScopeKey == right.EffectiveRuleScopeKey &&
               left.DeviceCode == right.DeviceCode &&
               left.DeviceName == right.DeviceName &&
               left.LastExecutionSummary == right.LastExecutionSummary &&
               left.LastExecutionOutcome == right.LastExecutionOutcome &&
               left.LastFaultClosureStatus == right.LastFaultClosureStatus;
    }

    private readonly record struct ResolvedRuleSelection(
        RecheckScheduleRule Rule,
        string RuleSource,
        string ScopeKey);

    private readonly record struct PreparedTaskExecution(
        RecheckTaskRecord Task,
        string OperatorName,
        string TriggerType,
        DateTimeOffset StartedAt,
        ResolvedRuleSelection RuleSelection);

    private sealed record TaskExecutionResult(
        string ExecutionId,
        string Outcome,
        string TaskStatus,
        string FaultClosureStatus,
        string Summary,
        string FailureReason,
        DeviceInspectionResult? InspectionResult,
        string PlaybackReviewSessionId,
        ExecutionResultKind ResultKind)
    {
        public static TaskExecutionResult Passed(
            string faultClosureStatus,
            string summary,
            DeviceInspectionResult? inspectionResult,
            string? playbackReviewSessionId)
        {
            return new TaskExecutionResult(
                Guid.NewGuid().ToString("N"),
                RecheckExecutionOutcomes.Passed,
                RecheckTaskStatuses.Completed,
                faultClosureStatus,
                summary,
                string.Empty,
                inspectionResult,
                playbackReviewSessionId ?? string.Empty,
                ExecutionResultKind.Passed);
        }

        public static TaskExecutionResult Failed(
            string faultClosureStatus,
            string summary,
            DeviceInspectionResult? inspectionResult,
            string failureReason,
            string? playbackReviewSessionId)
        {
            return new TaskExecutionResult(
                Guid.NewGuid().ToString("N"),
                RecheckExecutionOutcomes.Failed,
                RecheckTaskStatuses.Failed,
                faultClosureStatus,
                summary,
                failureReason,
                inspectionResult,
                playbackReviewSessionId ?? string.Empty,
                ExecutionResultKind.Failed);
        }

        public static TaskExecutionResult Error(string summary, string failureReason)
        {
            return new TaskExecutionResult(
                Guid.NewGuid().ToString("N"),
                RecheckExecutionOutcomes.Error,
                RecheckTaskStatuses.Failed,
                string.Empty,
                summary,
                failureReason,
                null,
                string.Empty,
                ExecutionResultKind.Error);
        }

        public static TaskExecutionResult Canceled(string summary, string faultClosureStatus = "")
        {
            return new TaskExecutionResult(
                Guid.NewGuid().ToString("N"),
                RecheckExecutionOutcomes.Canceled,
                RecheckTaskStatuses.Canceled,
                faultClosureStatus,
                summary,
                string.Empty,
                null,
                string.Empty,
                ExecutionResultKind.Canceled);
        }

        public static TaskExecutionResult Completed(string faultClosureStatus, string summary)
        {
            return new TaskExecutionResult(
                Guid.NewGuid().ToString("N"),
                RecheckExecutionOutcomes.Completed,
                RecheckTaskStatuses.Completed,
                faultClosureStatus,
                summary,
                string.Empty,
                null,
                string.Empty,
                ExecutionResultKind.Completed);
        }
    }

    private enum ExecutionResultKind
    {
        Passed,
        Failed,
        Error,
        Canceled,
        Completed
    }
}
